apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
data:
  # Helm의 b64enc 함수로 자동 인코딩
  MINIO_ROOT_USER: {{ .Values.minio.rootUser | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ .Values.minio.rootPassword | b64enc | quote }}